# Site settings
remote_theme: thiell/jekyll-theme-easy-wedding
title: Meredith & Stéphane
email: wedding-meresteph@thiell.com
url: https://thiell.github.io
description: "We're getting married and can't wait to celebrate with you!"
baseurl: "/"

plugins:
  - jekyll-compress-images
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
